apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fswd-frontend
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: fswd.devnss.com
    http:
      paths:
      - backend:
          serviceName: fswd-frontend
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
